version: '3.9'
services:
  react-ui:
    build: .
    ports:
      - '3070:3070'
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=mangalive
    # env_file:
    #   - ./.env
